CREATE DATABASE biblioteca_pessoal_1s2026;
USE biblioteca_pessoal_1s2026;
SHOW TABLES;
CREATE TABLE usuario(
id_usuario INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(128) NOT NULL UNIQUE,
data_cadastro DATE DEFAULT(CURRENT_DATE) NOT NULL
);


CREATE TABLE livro(
id_livro INT AUTO_INCREMENT PRIMARY KEY,
sinopse TEXT NOT NULL,
autor VARCHAR(128) NOT NULL,
editora VARCHAR(128) NOT NULL,
categoria VARCHAR(128) NOT NULL,
ano_publicacao DATE DEFAULT(CURRENT_DATE) NOT NULL

);
SHOW TABLES;